# SPDX-FileCopyrightText: 2026 Sandeep Bazar
# SPDX-License-Identifier: Apache-2.0
# Default-deny ingress; allow only DNS + HTTPS egress (the server talks to the hub API
# server over 443/6443). Tighten egress to the hub's IP/port in a real deployment.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ocm-mcp-server
  policyTypes: ["Ingress", "Egress"]
  ingress: []
  egress:
    - ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - ports:
        - {protocol: TCP, port: 443}
        - {protocol: TCP, port: 6443}
