#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Sandeep Bazar
# SPDX-License-Identifier: Apache-2.0
"""Render a self-contained, graphical HTML report from the e2e results JSONL.

Each JSONL record: {phase, title, why, cmd, output, status, kind?}.
Statuses drive colour: OK/PASS (green), FAIL (red), UNAVAILABLE/SKIP (amber),
INFO (blue), INJECT (purple), FIX (teal). Usage:

    e2e_report.py --results results.jsonl --out e2e-report.html [--title "..."]
"""
from __future__ import annotations

import argparse
import html
import json
from collections import OrderedDict
from datetime import datetime

STATUS = {
    "OK": ("#1a7f37", "#dafbe1"), "PASS": ("#1a7f37", "#dafbe1"),
    "FAIL": ("#cf222e", "#ffebe9"),
    "UNAVAILABLE": ("#9a6700", "#fff8c5"), "SKIP": ("#9a6700", "#fff8c5"),
    "INFO": ("#0969da", "#ddf4ff"),
    "INJECT": ("#8250df", "#fbefff"), "FIX": ("#1b7c83", "#d9f7f5"),
}


# The end-to-end story, top to bottom: (emoji, group/colour, title, one-liner).
FLOW = [
    ("\U0001f9f0", "setup", "Install & verify tools", "podman, kind, kubectl, clusteradm, helm"),
    ("☸️", "setup", "Bootstrap a real fleet", "1 hub + N spoke clusters, OCM, Kyverno, policies"),
    ("✨", "setup", "Enrich & seed fixtures", "add-ons, policies, ManifestWorks - so every tool has real data"),
    ("\U0001f50d", "read", "Investigate (read tools)", "inventory, health, placement, work, add-ons - free, no gate"),
    ("\U0001f6e1️", "gate", "Make a change, gated", "propose → Kyverno + guardrails → human token → apply (a bad token is refused)"),
    ("\U0001f4ac", "read", "Prompts & audit", "reusable runbooks and an append-only audit trail"),
    ("\U0001f4a5", "break", "Break something", "inject a failing rollout (ImagePullBackOff)"),
    ("\U0001fa7a", "break", "Diagnose", "health + events pinpoint the bad image"),
    ("\U0001f527", "fix", "Fix, through the gate", "propose the pinned image, approve, apply"),
    ("✅", "verify", "Verify recovery", "re-read health until the workload is healthy again"),
    ("\U0001f9f9", "clean", "Clean up", "delete only the clusters this run created"),
]
FLOW_LEDE = (
    "One command stands up a real multi-cluster Open Cluster Management fleet on kind, then "
    "drives the MCP server through every tool and prompt: it reads the fleet freely, but forces "
    "every change through policy checks and a human-approved token. It then deliberately breaks a "
    "workload and shows the agent diagnose and fix it, before tearing the fleet down. Green means "
    "the whole loop worked."
)


def flow_html() -> str:
    nodes = []
    for i, (ico, grp, title, sub) in enumerate(FLOW):
        nodes.append(
            f'<div class="fnode g-{grp}" style="--i:{i}"><span class="fdot"></span>'
            f'<span class="fico">{ico}</span><span class="ftext"><b>{esc(title)}</b>'
            f'<small>{esc(sub)}</small></span></div>'
        )
    return (
        '<section class="flowsec"><h2>What this end-to-end test does</h2>'
        f'<p class="lede">{esc(FLOW_LEDE)}</p>'
        f'<div class="flow">{"".join(nodes)}</div></section>'
    )


def esc(s: str) -> str:
    return html.escape(str(s or ""))


# Emoji per status, for the Markdown (wiki) report - GitHub wiki strips styled HTML.
MD_ICON = {
    "OK": "✅", "PASS": "✅", "FAIL": "❌",
    "UNAVAILABLE": "⚠️", "SKIP": "⚠️", "INFO": "ℹ️",
    "INJECT": "💥", "FIX": "🔧",
}


def markdown_report(records, phases, counts, title, generated) -> str:
    """A wiki-friendly Markdown version of the same report.

    GitHub wiki sanitizes the styled HTML report away, so the wiki gets this
    instead: the verdict, the counts, the end-to-end flow, and every step with
    its status, rationale, command, and (trimmed) output.
    """
    ok = counts.get("OK", 0) + counts.get("PASS", 0)
    fail = counts.get("FAIL", 0)
    warn = counts.get("UNAVAILABLE", 0) + counts.get("SKIP", 0)
    if fail:
        verdict = f"🔴 {fail} FAILED"
    elif warn:
        verdict = f"🟢 PASSED ({warn} expected-unavailable)"
    else:
        verdict = "🟢 ALL GREEN"

    out = [
        f"# {title}",
        "",
        ("<!-- Generated by hack/e2e-local.sh (hack/e2e_report.py). Do not edit by hand;"
         " re-run the end-to-end test to refresh. -->"),
        "",
        (f"**Verdict: {verdict}** &nbsp;·&nbsp; generated {generated} &nbsp;·&nbsp;"
         " local kind fleet via podman, Open Cluster Management hub"),
        "",
        "| Passed | Expected-unavailable | Failed | Total steps |",
        "|--:|--:|--:|--:|",
        f"| {ok} | {warn} | {fail} | {len(records)} |",
        "",
        ("> Reproduce locally with `./hack/e2e-local.sh` - one command stands up a real"
         " multi-cluster fleet on kind, drives every tool and prompt, breaks a workload and"
         " fixes it through the approval gate, then tears the fleet down."),
        "",
        "## What this end-to-end test does",
        "",
        FLOW_LEDE,
        "",
    ]
    for i, (ico, _grp, t, sub) in enumerate(FLOW, 1):
        out.append(f"{i}. {ico} **{t}** - {sub}")
    out.append("")

    for phase, items in phases.items():
        out.append(f"## {phase}")
        out.append("")
        for r in items:
            icon = MD_ICON.get(r.get("status", "INFO"), "•")
            status = r.get("status", "")
            title_r = r.get("title", "")
            out.append(f"### {icon} `{status}` {title_r}")
            out.append("")
            if r.get("why"):
                out.append(f"_{r['why']}_")
                out.append("")
            if r.get("cmd"):
                out.append("```")
                out.append(f"$ {r['cmd']}")
                out.append("```")
            body = str(r.get("output", "")).rstrip()
            if body:
                lines = body.splitlines()
                if len(lines) > 40:
                    lines = lines[:40] + [f"... ({len(body.splitlines()) - 40} more lines)"]
                out.append("```")
                out.extend(lines)
                out.append("```")
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--md", help="also write a wiki-friendly Markdown report to this path")
    ap.add_argument("--title", default="ocm-mcp-server - end-to-end test report")
    # Local wall-clock is intentional for a human-facing report header.
    ap.add_argument(
        "--generated",
        default=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),  # noqa: DTZ005
    )
    args = ap.parse_args()

    records = []
    with open(args.results) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError:
                # a truncated final line from an interrupted run must not kill the report
                continue

    phases: OrderedDict[str, list] = OrderedDict()
    counts: dict[str, int] = {}
    for r in records:
        phases.setdefault(r.get("phase", "Other"), []).append(r)
        counts[r.get("status", "INFO")] = counts.get(r.get("status", "INFO"), 0) + 1

    ok = counts.get("OK", 0) + counts.get("PASS", 0)
    fail = counts.get("FAIL", 0)
    warn = counts.get("UNAVAILABLE", 0) + counts.get("SKIP", 0)
    if fail:
        verdict = f"{fail} FAILED"
    elif warn:
        verdict = f"PASSED ({warn} expected-unavailable)"
    else:
        verdict = "ALL GREEN"
    verdict_col = "#1a7f37" if fail == 0 else "#cf222e"

    cards = []
    for phase, items in phases.items():
        rows = []
        for r in items:
            fg, bg = STATUS.get(r.get("status", "INFO"), ("#57606a", "#eaeef2"))
            cmd = esc(r.get("cmd", ""))
            out = esc(r.get("output", "")).rstrip()
            why = esc(r.get("why", ""))
            cmd_html = f'<div class="cmd">$ {cmd}</div>' if cmd else ""
            out_html = f'<pre class="out">{out}</pre>' if out else ""
            why_html = f'<div class="why">{why}</div>' if why else ""
            rows.append(f"""
            <div class="card">
              <div class="chead">
                <span class="badge" style="color:{fg};background:{bg}">{esc(r.get('status',''))}</span>
                <span class="ctitle">{esc(r.get('title',''))}</span>
              </div>
              {why_html}{cmd_html}{out_html}
            </div>""")
        cards.append(f'<section><h2>{esc(phase)}</h2>{"".join(rows)}</section>')

    def chip(label: str, n: int, col: str, bg: str) -> str:
        return f'<span class="chip" style="color:{col};background:{bg}"><b>{n}</b> {label}</span>'

    summary = "".join([
        chip("passed", ok, "#1a7f37", "#dafbe1"),
        chip("expected-unavailable", warn, "#9a6700", "#fff8c5"),
        chip("failed", fail, "#cf222e", "#ffebe9"),
        chip("total steps", len(records), "#0969da", "#ddf4ff"),
    ])

    doc = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(args.title)}</title>
<style>
:root{{color-scheme:light}}
*{{box-sizing:border-box}}
body{{margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
  background:#f6f8fa;color:#1f2328;line-height:1.5}}
header{{background:linear-gradient(135deg,#0b3d91,#1b7c83);color:#fff;padding:32px 24px}}
header h1{{margin:0 0 6px;font-size:24px}}
header .sub{{opacity:.9;font-size:14px}}
.verdict{{display:inline-block;margin-top:14px;padding:6px 16px;border-radius:999px;
  background:#fff;font-weight:800;font-size:15px;color:{verdict_col}}}
.wrap{{max-width:1080px;margin:0 auto;padding:24px}}
.summary{{display:flex;flex-wrap:wrap;gap:10px;margin:-12px 0 20px}}
.chip{{padding:8px 14px;border-radius:999px;font-size:13px}}
.chip b{{font-size:15px}}
section{{background:#fff;border:1px solid #d0d7de;border-radius:12px;padding:18px 18px 6px;margin:0 0 20px}}
section h2{{margin:0 0 14px;font-size:17px;color:#0b3d91;border-bottom:2px solid #eaeef2;padding-bottom:8px}}
.card{{border:1px solid #eaeef2;border-radius:10px;padding:12px 14px;margin:0 0 12px;background:#fbfcfe}}
.chead{{display:flex;align-items:center;gap:10px;margin-bottom:4px}}
.badge{{font-size:11px;font-weight:800;letter-spacing:.03em;padding:3px 9px;border-radius:999px}}
.ctitle{{font-weight:700;font-size:14.5px}}
.why{{color:#57606a;font-size:13.5px;margin:2px 0 8px}}
.cmd{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12.5px;background:#0d1117;
  color:#c9d1d9;padding:8px 12px;border-radius:8px;overflow-x:auto;white-space:pre;margin:6px 0}}
pre.out{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;background:#f6f8fa;
  border:1px solid #eaeef2;border-radius:8px;padding:10px 12px;overflow:auto;max-height:340px;margin:6px 0 4px}}
footer{{text-align:center;color:#8b949e;font-size:12px;padding:18px}}
.flowsec .lede{{color:#57606a;font-size:14px;margin:0 0 18px;max-width:840px}}
.flow{{position:relative;padding-left:36px}}
.flow::before{{content:"";position:absolute;left:15px;top:10px;bottom:10px;width:3px;border-radius:3px;
  background:linear-gradient(#0969da,#1b7c83,#9a6700,#8250df,#1a7f37,#57606a);
  background-size:100% 300%;animation:flow 7s linear infinite}}
@keyframes flow{{0%{{background-position:0 0}}100%{{background-position:0 -300%}}}}
.fnode{{position:relative;display:flex;align-items:center;gap:12px;background:#fff;border:1px solid #eaeef2;
  border-left:5px solid var(--c);border-radius:10px;padding:10px 14px;margin:0 0 12px;
  box-shadow:0 1px 2px rgba(0,0,0,.05);opacity:0;transform:translateY(10px);
  animation:rise .5s ease forwards;animation-delay:calc(var(--i)*.12s)}}
@keyframes rise{{to{{opacity:1;transform:none}}}}
.fdot{{position:absolute;left:-26px;width:14px;height:14px;border-radius:50%;background:var(--c);
  border:3px solid #fff;box-shadow:0 0 0 2px var(--c);animation:pulse 2.4s ease-in-out infinite;
  animation-delay:calc(var(--i)*.12s)}}
@keyframes pulse{{0%,100%{{box-shadow:0 0 0 2px var(--c)}}50%{{box-shadow:0 0 0 5px color-mix(in srgb,var(--c) 30%,transparent)}}}}
.fico{{font-size:20px;line-height:1}}
.ftext b{{font-size:14.5px}}
.ftext small{{display:block;color:#57606a;font-size:12.5px}}
.g-setup{{--c:#0969da}} .g-read{{--c:#1b7c83}} .g-gate{{--c:#9a6700}}
.g-break{{--c:#8250df}} .g-fix{{--c:#1b7c83}} .g-verify{{--c:#1a7f37}} .g-clean{{--c:#57606a}}
@media (prefers-reduced-motion:reduce){{.flow::before,.fnode,.fdot{{animation:none}}.fnode{{opacity:1;transform:none}}}}
</style></head><body>
<header><div class="wrap" style="padding-bottom:0">
  <h1>{esc(args.title)}</h1>
  <div class="sub">Generated {esc(args.generated)} - local kind fleet via podman, Open Cluster Management hub</div>
  <span class="verdict">{verdict}</span>
</div></header>
<div class="wrap">
  <div class="summary">{summary}</div>
  {flow_html()}
  {''.join(cards)}
</div>
<footer>Reproduce with <code>./hack/e2e-local.sh</code> - this report is generated, not checked in.</footer>
</body></html>"""

    with open(args.out, "w") as f:
        f.write(doc)
    print(f"report written: {args.out}  ({len(records)} steps, {ok} ok, {warn} unavailable, {fail} failed)")

    if args.md:
        with open(args.md, "w") as f:
            f.write(markdown_report(records, phases, counts, args.title, args.generated))
        print(f"markdown report written: {args.md}")


if __name__ == "__main__":
    main()
