#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Sandeep Bazar
# SPDX-License-Identifier: Apache-2.0
"""Render the unit-test + coverage wiki page and a Shields.io coverage badge.

Consumes the artifacts of a pytest run (JUnit XML + coverage.py JSON) and writes:
  - a Markdown wiki page (verdict, totals, per-module coverage table), and
  - a Shields "endpoint" JSON badge served raw from the wiki git repo.

Usage:
    unit_report.py --junit .unit-report/junit.xml --coverage .unit-report/coverage.json \
        --out-md wiki/Unit-Test-Results.md --out-badge wiki/coverage-badge.json
"""

from __future__ import annotations

import argparse
import json
import platform
import xml.etree.ElementTree as ET
from datetime import UTC, datetime
from pathlib import Path


def read_junit(path: Path) -> dict[str, float]:
    # Trusted input: this XML is generated by our own pytest run in the same
    # `make test-report` invocation, never fetched or user-supplied.
    root = ET.parse(path).getroot()
    suite = root if root.tag == "testsuite" else root.find("testsuite")
    if suite is None:
        raise SystemExit(f"no <testsuite> element found in {path}")
    totals = {k: float(suite.get(k, 0)) for k in ("tests", "failures", "errors", "skipped")}
    totals["time"] = float(suite.get("time", 0))
    return totals


def badge_color(percent: float) -> str:
    if percent >= 95:
        return "brightgreen"
    if percent >= 85:
        return "green"
    if percent >= 70:
        return "yellow"
    return "red"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--junit", type=Path, required=True)
    ap.add_argument("--coverage", type=Path, required=True)
    ap.add_argument("--out-md", type=Path, required=True)
    ap.add_argument("--out-badge", type=Path, required=True)
    args = ap.parse_args()

    junit = read_junit(args.junit)
    cov = json.loads(args.coverage.read_text())
    totals = cov["totals"]
    percent = float(totals["percent_covered"])
    broken = int(junit["failures"] + junit["errors"])
    verdict = "🟢 ALL PASSING" if broken == 0 else f"🔴 {broken} FAILED"
    generated = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# ocm-mcp-server - unit tests & coverage",
        "",
        "<!-- Generated by hack/unit_report.py (make test-report). Do not edit by hand. -->",
        "",
        (
            f"**Verdict: {verdict}** &nbsp;·&nbsp; generated {generated} &nbsp;·&nbsp; "
            f"Python {platform.python_version()}, all cluster interactions mocked"
        ),
        "",
        "| Tests | Passed | Failed | Skipped | Runtime | Statement coverage | Branch coverage |",
        "|--:|--:|--:|--:|--:|--:|--:|",
    ]
    stmt_pct = (
        100.0 * totals["covered_lines"] / totals["num_statements"]
        if totals["num_statements"]
        else 100.0
    )
    br_pct = (
        100.0 * totals.get("covered_branches", 0) / totals["num_branches"]
        if totals.get("num_branches")
        else 100.0
    )
    lines += [
        (
            f"| {int(junit['tests'])} | {int(junit['tests']) - broken - int(junit['skipped'])} "
            f"| {broken} | {int(junit['skipped'])} | {junit['time']:.2f}s "
            f"| {stmt_pct:.1f}% | {br_pct:.1f}% |"
        ),
        "",
        (
            "> Reproduce locally with `make test-report` - runs the full suite with branch "
            "coverage and refreshes this page, the coverage badge, and the browsable HTML "
            "coverage report in `.unit-report/htmlcov/`. CI enforces a 95% floor "
            "(`--cov-fail-under`) on every push and pull request."
        ),
        "",
        "## Coverage by module",
        "",
        "| Module | Statements | Missed | Branches | Missed | Coverage |",
        "|---|--:|--:|--:|--:|--:|",
    ]
    for path, info in sorted(cov["files"].items()):
        s = info["summary"]
        mod = path.replace("src/ocm_mcp_server/", "")
        lines.append(
            f"| `{mod}` | {s['num_statements']} | {s['missing_lines']} "
            f"| {s.get('num_branches', 0)} | {s.get('missing_branches', 0)} "
            f"| {s['percent_covered']:.1f}% |"
        )
    lines += [
        "",
        (
            f"**Total: {totals['num_statements']} statements, {totals.get('num_branches', 0)} "
            f"branches - {percent:.1f}% covered.**"
        ),
        "",
        (
            "See also: [end-to-end fleet test results](Test-Results) - a real kind fleet "
            "driven through every tool, the approval gate, and a break/fix loop."
        ),
    ]
    args.out_md.write_text("\n".join(lines) + "\n")

    args.out_badge.write_text(
        json.dumps(
            {
                "schemaVersion": 1,
                "label": "coverage",
                "message": f"{percent:.0f}%",
                "color": badge_color(percent),
            }
        )
        + "\n"
    )
    print(f"wrote {args.out_md} and {args.out_badge} ({percent:.1f}% covered)")


if __name__ == "__main__":
    main()
